version: '3.9'

services:
  httpd:
    build:
      context: ./httpd
    container_name: httpd
    ports:
      - 8080:80
    networks:
      - rails-stack
    depends_on:
      - rails
  rails:
    build:
      context: ./rails
    container_name: rails
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
    networks:
      - rails-stack
    depends_on:
      - postgres
  postgres:
    image: postgres:13.2
    container_name: postgres
    environment:
      POSTGRES_DB: rails
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
      POSTGRES_HOST_AUTH_METHOD: md5
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - postgres-pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - rails-stack
networks:
  rails-stack:
    ipam:
      config:
        - subnet: 172.20.16.0/24
volumes:
  postgres-pgdata: