default: &default
  adapter: postgresql
  encoding: utf-8
  host: postgres
  port: 5432
  database: rails
  username: rails
  password: rails
  schema_search_path: "public"
  pool: 100
  checkout_timeout: 5
  idle_timeout: 10

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default