default: &default
  adapter: postgresql
  encoding: utf-8
  host: postgresql01
  port: 5432
  database: rails01
  username: rails01
  password: rails01
  schema_search_path: "rails01"
  pool: 100
  checkout_timeout: 5
  idle_timeout: 10

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default